version: "2"

services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    networks:
      - webproxy

  prometheus:
    # image: prom/prometheus:latest
    build: prometheus/.
    ports:
      - 9090:9090
    networks:
      - webproxy

  alertmanager:
    # image: prom/alertmanager:latest
    build: alertmanager/.
    ports:
      - 9093:9093
    networks:
      - webproxy

  nodeexporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - webproxy

  collectdexporter:
    image: prom/collectd-exporter:latest
    entrypoint: prom/collectd-exporter --collectd.listen-address=":25826"
    ports:
      - 9103:9103
      - 25826:25826/udp
    networks:
      - webproxy

  smtpdev:
    image: rnwood/smtp4dev:latest
    ports:
      - 25
      - 5000:80
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge
