version: "2"

services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000

  prometheus:
    # image: prom/prometheus:latest
    build: prometheus/.
    ports:
      - 9090:9090

  alertmanager:
    # image: prom/alertmanager:latest
    build: alertmanager/.
    ports:
      - 9093:9093
