global:
    resolve_timeout: 1m
    slack_api_url: <SLACK_URL>

templates:
  - "/etc/alertmanager/templates/*"

route:
    receiver: 'slack-notifications'
    group_by: ['node_exporter']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 10s

    receivers:
      - name: 'slack-notifications'
        slack_configs:
         - channel: '#prometheus-testing'
           title: "PROMETHEUS Infrastructure ALERT"
           text: >-
             {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Annotations.description }}
                *Details:*
                {{ range .Labels.SortedPairs }} â€¢ *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
             {{ end }}
           send_resolved: true
